services:
  testssl:
    container_name: testssl
    networks:
      - caddy
    #ports:
      #- 5000:5000/tcp
    restart: on-failure
    image: hartge/testssl-web:v3.1

networks:
  caddy:
    external: true
